name: Simple CI

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      id: checkout
      uses: actions/checkout@v4

    - name: Test Local Action
      id: test-action
      uses: lars1974/gh-action-version-releaser@main  # Commit with the `v1` tag
      with:
        milliseconds: 1000

    - name: Print Output
      id: output
      run: echo "${{ steps.test-action.outputs.time }}"
